/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Element: typeof import('./src/components/M1/element.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoBackground: typeof import('./src/components/M2/video/VideoBackground.vue')['default']
  }
}
